// Default settings and built-in keyword packs.
//
// Keywords are matched case-insensitively against video titles (and optionally
// channel names / description snippets). A keyword only matches as a whole word
// or phrase: "ai" matches "AI art" and "#ai" but not "said" or "Thailand".
// Spaces inside a keyword also match "-", "_" or nothing, so "ai art" matches
// "AI-art" and "#aiart". A trailing plural "s" is matched automatically.

export const KEYWORD_PACKS = {
  aiGenerated: {
    label: 'AI-generated videos',
    description: 'Videos made with AI video, image, music or voice generators ("AI slop").',
    keywords: [
      // Explicit disclosure
      'ai generated',
      'generated by ai',
      'generated with ai',
      'generated using ai',
      'made with ai',
      'made by ai',
      'made using ai',
      'created with ai',
      'created by ai',
      'created using ai',
      'ai made',
      'ai created',
      // Formats
      'ai art',
      'ai artwork',
      'ai animation',
      'ai animated',
      'ai video',
      'ai film',
      'ai movie',
      'ai short film',
      'ai trailer',
      'ai cinema',
      'ai music',
      'ai song',
      'ai cover',
      'ai voice',
      'ai voiceover',
      'ai narrated',
      'ai narration',
      'ai singing',
      'ai remix',
      'ai version',
      'ai reimagined',
      'ai remake',
      'ai slop',
      'ai story',
      'ai storytime',
      'ai cat',
      'ai dog',
      'ai baby',
      'ai babies',
      'ai animal',
      'ai fruit',
      // Generators
      'sora ai',
      'openai sora',
      'sora 2',
      'made with sora',
      'veo 3',
      'veo3',
      'google veo',
      'kling ai',
      'hailuo',
      'minimax video',
      'runway gen',
      'runwayml',
      'pika labs',
      'luma dream machine',
      'midjourney',
      'stable diffusion',
      'dall-e',
      'dalle',
      'leonardo ai',
      'suno',
      'suno ai',
      'udio',
      'elevenlabs',
      // Hashtags
      '#ai',
      '#aiart',
      '#aigenerated',
      '#aivideo',
      '#aimusic',
      '#aicover',
      '#aianimation',
      '#aifilm',
      '#sora2',
      '#soraai',
      '#veo3',
      '#midjourney',
      '#suno',
      '#kling',
      '#aiartwork',
      '#aislop',
    ],
  },
  aiTopics: {
    label: 'AI news, hype & tutorials',
    description: 'Anything about AI: ChatGPT, LLMs, AI tools, AI news. Aggressive — off by default.',
    keywords: [
      'ai',
      'a.i.',
      'artificial intelligence',
      'generative ai',
      'genai',
      'chatgpt',
      'chat gpt',
      'gpt',
      'openai',
      'anthropic',
      'claude ai',
      'gemini ai',
      'google gemini',
      'copilot',
      'grok',
      'deepseek',
      'perplexity ai',
      'mistral ai',
      'llm',
      'large language model',
      'agi',
      'machine learning',
      'deep learning',
      'neural network',
      'prompt engineering',
      'ai agent',
      'ai tool',
      'ai news',
      'deepfake',
    ],
  },
};

export const DEFAULT_SETTINGS = {
  enabled: true,
  // 'hide' removes matching videos; 'blur' blurs them behind a label you can click through.
  mode: 'hide',
  packs: { aiGenerated: true, aiTopics: false },
  // Extra keywords. Wrap in slashes for a regular expression: /\bai\s+\w+\s+cat/i
  customKeywords: [],
  // Words from the built-in packs that should never trigger a match.
  ignoredKeywords: [],
  // Channels are { key, name } where key is "@handle", "UC…" channel id, or "name:<display name>".
  blockedChannels: [],
  allowedChannels: [],
  matchChannelNames: true,
  matchDescriptions: true,
  // On a watch page, detect YouTube's "Altered or synthetic content" label.
  detectDisclosure: true,
  // Automatically add channels that use the synthetic-content label to the block list.
  autoBlockDisclosed: false,
  // Show the small AI Filter bar on watch and channel pages.
  showPageBar: true,
  // Hide YouTube Playables (in-browser games): the home-feed shelf, game cards and the sidebar entry.
  hidePlayables: true,
  // Hide YouTube Shorts everywhere; Shorts links open in the normal video player instead.
  hideShorts: true,
  // On video pages, hide YouTube's top bar and size the player to fill the window.
  cinemaWatch: true,
};

export const SETTINGS_KEY = 'aiFilterSettings';
